version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      TZ: Europe/Warsaw
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
