imports:
    - { resource: config.yml }

monolog:
    channels: ["cli"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        cli:
            level: info
            type: stream
            path: "%kernel.logs_dir%/cli.log"
            channels: [cli]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
